---
Resources:
  ApiGatewayUsagePlan1:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
        - ApiId: test_api1
          Stage: test_api_stage
        - ApiId: test_api2
          Stage: test_api_stage
      UsagePlanName: testusageplan1

  ApiGatewayUsagePlan2:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
        - ApiId: test_api3
          Stage: test_api_stage
        - ApiId: test_api4
          Stage: test_api_stage
      UsagePlanName: testusageplan1

  ApiGatewayRestApi1:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: test_api_1

  ApiGatewayRestApi2:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: test_api_2

  ApiGatewayRestApi3:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: test_api_3

  ApiGatewayRestApi4:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: test_api_4